Add Windows console colour support
New option in configure script: `--use-color-woe32`
and macro: `VP_USE_COLOR_WOE32`

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -43,6 +43,7 @@ ifndef_guards="yes"
 # Default feature values
 use_color="unset" #deprecated
 use_color_ansi="no"
+use_color_woe32="no"
 use_fullwidth="no"
 use_gettext="no"
 use_sysexits="no"
@@ -138,6 +139,7 @@ Installation directories:
 
 Optional features (using --use-FEATURE [all are off by default]):
   color-ansi          Enable colour support using ANSI escape codes
+  color-woe32            "      "      "      "   the Windows Console API
   fullwidth           Enable fullwidth (CJK) character output using UTF-8
   gettext             Enable message translations using gettext
   posixtime           Use higher-resolution time for better random numbers
@@ -165,8 +167,12 @@ fi
 
 test "$is_verbose" = "yes" && echo "Entering verbose mode."
 
-# TODO: in future versions where more colour output formats exist,
-#       check to make sure only one is enabled at once
+# Make sure only one `--use-color-TYPE' flag is set
+if test "$use_color_ansi" = "yes" && test "$use_color_woe32" = "yes"; then
+	echo "$log_e: Cannot use more than one \`--use-color-TYPE'"\
+	     "flag at once." >&2
+	exit 1
+fi
 
 # Check for deprecated `--use-color' flag
 if test "$use_color" != "unset"; then
@@ -309,6 +315,29 @@ else
 	exit 1
 fi
 
+# Check for Windows API
+if test "$use_color_woe32" = "yes"; then
+	test "$is_quiet" = "no" &&
+	  echo $n "Checking for Windows header files... "
+	cat >conftest.c <<_EOF
+#include <windows.h>
+
+int main() { return 0; }
+_EOF
+	(eval $CC $CFLAGS conftest.c -o conftest) 2>conftest.err
+	rm -f conftest.o conftest.c conftest
+	if test ! -s conftest.err; then
+		test "$is_quiet" = "no" && echo "found."
+		rm -f conftest.err
+	else
+		test "$is_quiet" = "no" && echo "not found."
+		echo "$log_e: Cannot find \`windows.h'." >&2
+		echo "$log_e: Specify a valid include dir in your CFLAGS with"\
+		     "\`CFLAGS=-I/path/to/dir' when running this script." >&2
+		exit 1
+	fi
+fi
+
 # Check for libintl (gettext)
 if test "$use_gettext" = "yes"; then
 	test "$is_quiet" = "no" &&
@@ -394,6 +423,8 @@ test "$is_verbose" = "yes" &&
 feature_CFLAGS=""
 test "$use_color_ansi" = "yes" &&
   feature_CFLAGS="$feature_CFLAGS -DVP_USE_COLOR_ANSI"
+test "$use_color_woe32" = "yes" &&
+  feature_CFLAGS="$feature_CFLAGS -DVP_USE_COLOR_WOE32"
 test "$use_fullwidth" = "yes" &&
   feature_CFLAGS="$feature_CFLAGS -DVP_USE_FULLWIDTH"
 test "$use_gettext" = "yes" &&
